#!/usr/bin/env python

# This file was written by Michael P Andersen, and then modified by
# me to generate C code instead of Go code.

#hopefully this works on python2 and python3
from __future__ import print_function
import requests
import yaml #this is pyaml on pip
import sys
import os
import os.path
import textwrap

rq = requests.get("https://raw.githubusercontent.com/immesys/bw2_pid/master/allocations.yaml")
if rq.status_code != 200:
    print ("Could not obtain allocations file from GitHub")
    sys.exit(1)

doc = yaml.load(rq.text)
def parsedot(s):
    i = s.split(".")
    return (int(i[0])<<24) + (int(i[1])<<16) + (int(i[2]) << 8) + int(i[3])
subnets = sorted([(int(k.split("/")[1]), parsedot(k.split("/")[0]), k ) for k in doc.keys()])

def gen_golang(subnets, doc):
    curpath=os.path.realpath(__file__)
    package = curpath.split("/")[-2]
    ofgo = open("ponames.h", "w")

    print("#ifndef PONAMES_H", file=ofgo)
    print("#define PONAMES_H\n", file=ofgo)
    print("//This file is autogenerated from https://github.com/immesys/bw2_pid/blob/master/allocations.yaml\n", file=ofgo)
    for i in subnets:
        d = doc[i[2]]
        print("//%s (%s): %s" %(d["sym"], i[2], d["short"]), file=ofgo)
        print("//"+"\n//".join(textwrap.wrap(d["desc"], 77)), file=ofgo)
        print("#define BW2_PO_NUM_%s %d" % (d["sym"].upper(), i[1]), file=ofgo)
        print("#define BW2_PO_DF_MASK_%s \"%s\"" % (d["sym"].upper(), i[2]), file=ofgo)
        print("#define BW2_PO_DF_%s \"%s\"" % (d["sym"].upper(), i[2].split("/")[0]), file=ofgo)
        print("#define BW2_PO_MASK_%s %d" % (d["sym"].upper(), i[0]), file=ofgo)
        print("", file=ofgo)
    print("#endif", file=ofgo)
    ofgo.close()


gen_golang(subnets, doc)
