#ifndef BW2_PONAMES_H
#define BW2_PONAMES_H

//This file is autogenerated from https://github.com/immesys/bw2_pid/blob/master/allocations.yaml

//Binary (0.0.0.0/4): Binary protocols
//This is a superclass for classes that are generally unreadable in their plain
//form and require translation.
#define BW2_PO_NUM_BINARY 0
#define BW2_PO_DF_MASK_BINARY "0.0.0.0/4"
#define BW2_PO_DF_BINARY "0.0.0.0"
#define BW2_PO_MASK_BINARY 4

//Text (64.0.0.0/4): Human readable text
//This is a superclass for classes that are moderately understandable if they
//are read directly in their binary form. Generally these are protocols that
//were designed specifically to be human readable.
#define BW2_PO_NUM_TEXT 1073741824
#define BW2_PO_DF_MASK_TEXT "64.0.0.0/4"
#define BW2_PO_DF_TEXT "64.0.0.0"
#define BW2_PO_MASK_TEXT 4

//Blob (1.0.0.0/8): Blob
//This is a class for schemas that do not use a public encoding format. In
//general it should be avoided. Schemas below this should include the key
//"readme" with a url to a description of the schema that is sufficiently
//detailed to allow for a developer to reverse engineer the protocol if
//required.
#define BW2_PO_NUM_BLOB 16777216
#define BW2_PO_DF_MASK_BLOB "1.0.0.0/8"
#define BW2_PO_DF_BLOB "1.0.0.0"
#define BW2_PO_MASK_BLOB 8

//MsgPack (2.0.0.0/8): MsgPack
//This class is for schemas that are represented in MsgPack
#define BW2_PO_NUM_MSGPACK 33554432
#define BW2_PO_DF_MASK_MSGPACK "2.0.0.0/8"
#define BW2_PO_DF_MSGPACK "2.0.0.0"
#define BW2_PO_MASK_MSGPACK 8

//CapnP (3.0.0.0/8): Captain Proto
//This class is for captain proto interfaces. Schemas below this should include
//the key "schema" with a url to their .capnp file
#define BW2_PO_NUM_CAPNP 50331648
#define BW2_PO_DF_MASK_CAPNP "3.0.0.0/8"
#define BW2_PO_DF_CAPNP "3.0.0.0"
#define BW2_PO_MASK_CAPNP 8

//JSON (65.0.0.0/8): JSON
//This class is for schemas that are represented in JSON
#define BW2_PO_NUM_JSON 1090519040
#define BW2_PO_DF_MASK_JSON "65.0.0.0/8"
#define BW2_PO_DF_JSON "65.0.0.0"
#define BW2_PO_MASK_JSON 8

//XML (66.0.0.0/8): XML
//This class is for schemas that are represented in XML
#define BW2_PO_NUM_XML 1107296256
#define BW2_PO_DF_MASK_XML "66.0.0.0/8"
#define BW2_PO_DF_XML "66.0.0.0"
#define BW2_PO_MASK_XML 8

//YAML (67.0.0.0/8): YAML
//This class is for schemas that are represented in YAML
#define BW2_PO_NUM_YAML 1124073472
#define BW2_PO_DF_MASK_YAML "67.0.0.0/8"
#define BW2_PO_DF_YAML "67.0.0.0"
#define BW2_PO_MASK_YAML 8

//BWRoutingObject (0.0.0.0/24): Bosswave Routing Object
//This class and schema block is reserved for bosswave routing objects
//represented using the full PID.
#define BW2_PO_NUM_BWROUTINGOBJECT 0
#define BW2_PO_DF_MASK_BWROUTINGOBJECT "0.0.0.0/24"
#define BW2_PO_DF_BWROUTINGOBJECT "0.0.0.0"
#define BW2_PO_MASK_BWROUTINGOBJECT 24

//LogDict (2.0.1.0/24): LogDict
//This class is for log messages encoded in msgpack
#define BW2_PO_NUM_LOGDICT 33554688
#define BW2_PO_DF_MASK_LOGDICT "2.0.1.0/24"
#define BW2_PO_DF_LOGDICT "2.0.1.0"
#define BW2_PO_MASK_LOGDICT 24

//TSTaggedMP (2.0.3.0/24): TSTaggedMP
//This superclass describes "ts"->int64 tagged msgpack objects. The timestamp
//is used for merging entries and determining which is later and should be the
//final value.
#define BW2_PO_NUM_TSTAGGEDMP 33555200
#define BW2_PO_DF_MASK_TSTAGGEDMP "2.0.3.0/24"
#define BW2_PO_DF_TSTAGGEDMP "2.0.3.0"
#define BW2_PO_MASK_TSTAGGEDMP 24

//HamiltonBase (2.0.4.0/24): Hamilton Messages
//This is the base class for messages used with the Hamilton motes. The only
//key guaranteed is "#" that contains a uint16 representation of the serial of
//the mote the message is destined for or originated from.
#define BW2_PO_NUM_HAMILTONBASE 33555456
#define BW2_PO_DF_MASK_HAMILTONBASE "2.0.4.0/24"
#define BW2_PO_DF_HAMILTONBASE "2.0.4.0"
#define BW2_PO_MASK_HAMILTONBASE 24

//BW2ChatMessages (2.0.7.0/24): BW2ChatMessages
//These are MsgPack dictionaries sent for the BW2Chat program
//(https://github.com/gtfierro/bw2chat)
#define BW2_PO_NUM_BW2CHATMESSAGES 33556224
#define BW2_PO_DF_MASK_BW2CHATMESSAGES "2.0.7.0/24"
#define BW2_PO_DF_BW2CHATMESSAGES "2.0.7.0"
#define BW2_PO_MASK_BW2CHATMESSAGES 24

//Giles_Messages (2.0.8.0/24): Giles Messages
//Messages for communicating with a Giles archiver
#define BW2_PO_NUM_GILES_MESSAGES 33556480
#define BW2_PO_DF_MASK_GILES_MESSAGES "2.0.8.0/24"
#define BW2_PO_DF_GILES_MESSAGES "2.0.8.0"
#define BW2_PO_MASK_GILES_MESSAGES 24

//UniqueObjectStream (2.0.9.0/24): Unique Object Stream
//An object that is part of a (possibly ordered) stream, identified by UUID. It
//must contain at least a UUID key uniquely identifying the collection
#define BW2_PO_NUM_UNIQUEOBJECTSTREAM 33556736
#define BW2_PO_DF_MASK_UNIQUEOBJECTSTREAM "2.0.9.0/24"
#define BW2_PO_DF_UNIQUEOBJECTSTREAM "2.0.9.0"
#define BW2_PO_MASK_UNIQUEOBJECTSTREAM 24

//HamiltonTelemetry (2.0.4.64/26): Hamilton Telemetry
//This object contains a "#" field for the serial number, as well as possibly
//containing an "A" field with a list of X, Y, and Z accelerometer values. A
//"T" field containing the temperature as an integer in degrees C multiplied by
//10000, and an "L" field containing the illumination in Lux.
#define BW2_PO_NUM_HAMILTONTELEMETRY 33555520
#define BW2_PO_DF_MASK_HAMILTONTELEMETRY "2.0.4.64/26"
#define BW2_PO_DF_HAMILTONTELEMETRY "2.0.4.64"
#define BW2_PO_MASK_HAMILTONTELEMETRY 26

//TimeseriesReading (2.0.9.16/28): Timeseries Reading
//Map with at least these keys: - UUID: string UUID uniquely identifying this
//timeseries - Time: int64 timestamp, UTC nanoseconds - Value: float64 value
#define BW2_PO_NUM_TIMESERIESREADING 33556752
#define BW2_PO_DF_MASK_TIMESERIESREADING "2.0.9.16/28"
#define BW2_PO_DF_TIMESERIESREADING "2.0.9.16"
#define BW2_PO_MASK_TIMESERIESREADING 28

//ROAccessDChainHash (0.0.0.1/32): Access DChain hash
//An access dchain hash
#define BW2_PO_NUM_ROACCESSDCHAINHASH 1
#define BW2_PO_DF_MASK_ROACCESSDCHAINHASH "0.0.0.1/32"
#define BW2_PO_DF_ROACCESSDCHAINHASH "0.0.0.1"
#define BW2_PO_MASK_ROACCESSDCHAINHASH 32

//ROAccessDChain (0.0.0.2/32): Access DChain
//An access dchain
#define BW2_PO_NUM_ROACCESSDCHAIN 2
#define BW2_PO_DF_MASK_ROACCESSDCHAIN "0.0.0.2/32"
#define BW2_PO_DF_ROACCESSDCHAIN "0.0.0.2"
#define BW2_PO_MASK_ROACCESSDCHAIN 32

//ROPermissionDChainHash (0.0.0.17/32): Permission DChain hash
//A permission dchain hash
#define BW2_PO_NUM_ROPERMISSIONDCHAINHASH 17
#define BW2_PO_DF_MASK_ROPERMISSIONDCHAINHASH "0.0.0.17/32"
#define BW2_PO_DF_ROPERMISSIONDCHAINHASH "0.0.0.17"
#define BW2_PO_MASK_ROPERMISSIONDCHAINHASH 32

//ROPermissionDChain (0.0.0.18/32): Permission DChain
//A permission dchain
#define BW2_PO_NUM_ROPERMISSIONDCHAIN 18
#define BW2_PO_DF_MASK_ROPERMISSIONDCHAIN "0.0.0.18/32"
#define BW2_PO_DF_ROPERMISSIONDCHAIN "0.0.0.18"
#define BW2_PO_MASK_ROPERMISSIONDCHAIN 32

//ROAccessDOT (0.0.0.32/32): Access DOT
//An access DOT
#define BW2_PO_NUM_ROACCESSDOT 32
#define BW2_PO_DF_MASK_ROACCESSDOT "0.0.0.32/32"
#define BW2_PO_DF_ROACCESSDOT "0.0.0.32"
#define BW2_PO_MASK_ROACCESSDOT 32

//ROPermissionDOT (0.0.0.33/32): Permission DOT
//A permission DOT
#define BW2_PO_NUM_ROPERMISSIONDOT 33
#define BW2_PO_DF_MASK_ROPERMISSIONDOT "0.0.0.33/32"
#define BW2_PO_DF_ROPERMISSIONDOT "0.0.0.33"
#define BW2_PO_MASK_ROPERMISSIONDOT 32

//ROEntity (0.0.0.48/32): Entity
//An entity
#define BW2_PO_NUM_ROENTITY 48
#define BW2_PO_DF_MASK_ROENTITY "0.0.0.48/32"
#define BW2_PO_DF_ROENTITY "0.0.0.48"
#define BW2_PO_MASK_ROENTITY 32

//ROOriginVK (0.0.0.49/32): Origin verifying key
//The origin VK of a message that does not contain a PAC
#define BW2_PO_NUM_ROORIGINVK 49
#define BW2_PO_DF_MASK_ROORIGINVK "0.0.0.49/32"
#define BW2_PO_DF_ROORIGINVK "0.0.0.49"
#define BW2_PO_MASK_ROORIGINVK 32

//ROEntityWKey (0.0.0.50/32): Entity with signing key
//An entity with signing key
#define BW2_PO_NUM_ROENTITYWKEY 50
#define BW2_PO_DF_MASK_ROENTITYWKEY "0.0.0.50/32"
#define BW2_PO_DF_ROENTITYWKEY "0.0.0.50"
#define BW2_PO_MASK_ROENTITYWKEY 32

//RODRVK (0.0.0.51/32): Designated router verifying key
//a 32 byte designated router verifying key
#define BW2_PO_NUM_RODRVK 51
#define BW2_PO_DF_MASK_RODRVK "0.0.0.51/32"
#define BW2_PO_DF_RODRVK "0.0.0.51"
#define BW2_PO_MASK_RODRVK 32

//ROExpiry (0.0.0.64/32): Expiry
//Sets an expiry for the message
#define BW2_PO_NUM_ROEXPIRY 64
#define BW2_PO_DF_MASK_ROEXPIRY "0.0.0.64/32"
#define BW2_PO_DF_ROEXPIRY "0.0.0.64"
#define BW2_PO_MASK_ROEXPIRY 32

//RORevocation (0.0.0.80/32): Revocation
//A revocation for an Entity or a DOT
#define BW2_PO_NUM_ROREVOCATION 80
#define BW2_PO_DF_MASK_ROREVOCATION "0.0.0.80/32"
#define BW2_PO_DF_ROREVOCATION "0.0.0.80"
#define BW2_PO_MASK_ROREVOCATION 32

//BinaryActuation (1.0.1.0/32): Binary actuation
//This payload object is one byte long, 0x00 for off, 0x01 for on.
#define BW2_PO_NUM_BINARYACTUATION 16777472
#define BW2_PO_DF_MASK_BINARYACTUATION "1.0.1.0/32"
#define BW2_PO_DF_BINARYACTUATION "1.0.1.0"
#define BW2_PO_MASK_BINARYACTUATION 32

//BWMessage (1.0.1.1/32): Packed Bosswave Message
//This object contains an entire signed and encoded bosswave message
#define BW2_PO_NUM_BWMESSAGE 16777473
#define BW2_PO_DF_MASK_BWMESSAGE "1.0.1.1/32"
#define BW2_PO_DF_BWMESSAGE "1.0.1.1"
#define BW2_PO_MASK_BWMESSAGE 32

//Double (1.0.2.0/32): Double
//This payload is an 8 byte long IEEE 754 double floating point value encoded
//in little endian. This should only be used if the semantic meaning is obvious
//in the context, otherwise a PID with a more specific semantic meaning should
//be used.
#define BW2_PO_NUM_DOUBLE 16777728
#define BW2_PO_DF_MASK_DOUBLE "1.0.2.0/32"
#define BW2_PO_DF_DOUBLE "1.0.2.0"
#define BW2_PO_MASK_DOUBLE 32

//Wavelet (1.0.6.1/32): Wavelet binary
//This object contains a BOSSWAVE Wavelet
#define BW2_PO_NUM_WAVELET 16778753
#define BW2_PO_DF_MASK_WAVELET "1.0.6.1/32"
#define BW2_PO_DF_WAVELET "1.0.6.1"
#define BW2_PO_MASK_WAVELET 32

//SpawnpointLog (2.0.2.0/32): Spawnpoint stdout
//This contains stdout data from a spawnpoint container. It is a msgpacked
//dictionary that contains a "service" key, a "time" key (unix nano timestamp)
//and a "contents" key and a "spalias" key.
#define BW2_PO_NUM_SPAWNPOINTLOG 33554944
#define BW2_PO_DF_MASK_SPAWNPOINTLOG "2.0.2.0/32"
#define BW2_PO_DF_SPAWNPOINTLOG "2.0.2.0"
#define BW2_PO_MASK_SPAWNPOINTLOG 32

//SpawnpointHeartbeat (2.0.2.1/32): SpawnPoint heartbeat
//A heartbeat message from spawnpoint. It is a msgpack dictionary that contains
//the keys "Alias", "Time", "TotalMem", "TotalCpuShares", "AvailableMem", and
//"AvailableCpuShares".
#define BW2_PO_NUM_SPAWNPOINTHEARTBEAT 33554945
#define BW2_PO_DF_MASK_SPAWNPOINTHEARTBEAT "2.0.2.1/32"
#define BW2_PO_DF_SPAWNPOINTHEARTBEAT "2.0.2.1"
#define BW2_PO_MASK_SPAWNPOINTHEARTBEAT 32

//SpawnpointSvcHb (2.0.2.2/32): SpawnPoint Service Heartbeat
//A heartbeat from spawnpoint about a currently running service. It is a
//msgpack dictionary that contains the keys "SpawnpointURI", "Name", "Time",
//"MemAlloc", and "CpuShares".
#define BW2_PO_NUM_SPAWNPOINTSVCHB 33554946
#define BW2_PO_DF_MASK_SPAWNPOINTSVCHB "2.0.2.2/32"
#define BW2_PO_DF_SPAWNPOINTSVCHB "2.0.2.2"
#define BW2_PO_MASK_SPAWNPOINTSVCHB 32

//SMetadata (2.0.3.1/32): Simple Metadata entry
//This contains a simple "val" string and "ts" int64 metadata entry. The key is
//determined by the URI. Other information MAY be present in the msgpacked
//object. The timestamp is used for merging metadata entries.
#define BW2_PO_NUM_SMETADATA 33555201
#define BW2_PO_DF_MASK_SMETADATA "2.0.3.1/32"
#define BW2_PO_DF_SMETADATA "2.0.3.1"
#define BW2_PO_MASK_SMETADATA 32

//HSBLightMessage (2.0.5.1/32): HSBLight Message
//This object may contain "hue", "saturation", "brightness" fields with a float
//from 0 to 1. It may also contain an "state" key with a boolean. Omitting
//fields leaves them at their previous state.
#define BW2_PO_NUM_HSBLIGHTMESSAGE 33555713
#define BW2_PO_DF_MASK_HSBLIGHTMESSAGE "2.0.5.1/32"
#define BW2_PO_DF_HSBLIGHTMESSAGE "2.0.5.1"
#define BW2_PO_MASK_HSBLIGHTMESSAGE 32

//InterfaceDescriptor (2.0.6.1/32): InterfaceDescriptor
//This object is used to describe an interface. It contains "uri",
//"iface","svc","namespace" "prefix" and "metadata" keys.
#define BW2_PO_NUM_INTERFACEDESCRIPTOR 33555969
#define BW2_PO_DF_MASK_INTERFACEDESCRIPTOR "2.0.6.1/32"
#define BW2_PO_DF_INTERFACEDESCRIPTOR "2.0.6.1"
#define BW2_PO_MASK_INTERFACEDESCRIPTOR 32

//BW2Chat_CreateRoomMessage (2.0.7.1/32): BW2Chat_CreateRoomMessage
//A dictionary with a single key "Name" indicating the room to be created. This
//will likely be deprecated.
#define BW2_PO_NUM_BW2CHAT_CREATEROOMMESSAGE 33556225
#define BW2_PO_DF_MASK_BW2CHAT_CREATEROOMMESSAGE "2.0.7.1/32"
#define BW2_PO_DF_BW2CHAT_CREATEROOMMESSAGE "2.0.7.1"
#define BW2_PO_MASK_BW2CHAT_CREATEROOMMESSAGE 32

//BW2Chat_ChatMessage (2.0.7.2/32): BW2Chat_ChatMessage
//A textual message to be sent to all members of a chatroom. This is a
//dictionary with three keys: 'Room', the name of the room to publish to (this
//is actually implicit in the publishing), 'From', the alias you are using for
//the chatroom, and 'Message', the actual string to be displayed to all users
//in the room.
#define BW2_PO_NUM_BW2CHAT_CHATMESSAGE 33556226
#define BW2_PO_DF_MASK_BW2CHAT_CHATMESSAGE "2.0.7.2/32"
#define BW2_PO_DF_BW2CHAT_CHATMESSAGE "2.0.7.2"
#define BW2_PO_MASK_BW2CHAT_CHATMESSAGE 32

//BW2Chat_JoinRoom (2.0.7.3/32): BW2Chat_JoinRoom
//Notify users in the chatroom that you have joined. Dictionary with a single
//key "Alias" that has a value of your nickname
#define BW2_PO_NUM_BW2CHAT_JOINROOM 33556227
#define BW2_PO_DF_MASK_BW2CHAT_JOINROOM "2.0.7.3/32"
#define BW2_PO_DF_BW2CHAT_JOINROOM "2.0.7.3"
#define BW2_PO_MASK_BW2CHAT_JOINROOM 32

//BW2Chat_LeaveRoom (2.0.7.4/32): BW2Chat_LeaveRoom
//Notify users in the chatroom that you have left. Dictionary with a single key
//"Alias" that has a value of your nickname
#define BW2_PO_NUM_BW2CHAT_LEAVEROOM 33556228
#define BW2_PO_DF_MASK_BW2CHAT_LEAVEROOM "2.0.7.4/32"
#define BW2_PO_DF_BW2CHAT_LEAVEROOM "2.0.7.4"
#define BW2_PO_MASK_BW2CHAT_LEAVEROOM 32

//GilesArchiveRequest (2.0.8.0/32): Giles Archive Request
//A MsgPack dictionary with the following keys: - URI (optional): the URI to
//subscribe to for data - PO (required): which PO object type to extract from
//messages on the URI - UUID (optional): the UUID to use, else it is
//consistently autogenerated. - Value (required): ObjectBuilder expression for
//how to extract the value - Time (optional): ObjectBuilder expression for how
//to extract any timestamp - TimeParse (optional): How to parse that timestamp
//- MetadataURI (optional): a base URI to scan for metadata (expands to
//uri/!meta/+) - MetadataBlock (optional): URI containing a key-value structure
//of metadata - MetadataExpr (optional): ObjectBuilder expression to search for
//a key-value structure in the current message for metadata ObjectBuilder
//expressions are documented at:
//https://github.com/gtfierro/giles2/tree/master/objectbuilder
#define BW2_PO_NUM_GILESARCHIVEREQUEST 33556480
#define BW2_PO_DF_MASK_GILESARCHIVEREQUEST "2.0.8.0/32"
#define BW2_PO_DF_GILESARCHIVEREQUEST "2.0.8.0"
#define BW2_PO_MASK_GILESARCHIVEREQUEST 32

//GilesKeyValueQuery (2.0.8.1/32): Giles Key Value Query
//Expresses a query to a Giles instance. Expects 2 keys: - Query: A Giles query
//string following syntax at
//https://gtfierro.github.io/giles2/interface/#querylang - Nonce: a unique
//uint32 number for identifying the results of this query
#define BW2_PO_NUM_GILESKEYVALUEQUERY 33556481
#define BW2_PO_DF_MASK_GILESKEYVALUEQUERY "2.0.8.1/32"
#define BW2_PO_DF_GILESKEYVALUEQUERY "2.0.8.1"
#define BW2_PO_MASK_GILESKEYVALUEQUERY 32

//GilesMetadataResponse (2.0.8.2/32): Giles Metadata Response
//Dictionary containing metadata results for a query. Has 2 keys: - Nonce: the
//uint32 number corresponding to the query nonce that generated this metadata
//response - Data: list of GilesKeyValueMetadata (2.0.8.3) objects
#define BW2_PO_NUM_GILESMETADATARESPONSE 33556482
#define BW2_PO_DF_MASK_GILESMETADATARESPONSE "2.0.8.2/32"
#define BW2_PO_DF_GILESMETADATARESPONSE "2.0.8.2"
#define BW2_PO_MASK_GILESMETADATARESPONSE 32

//GilesKeyValueMetadata (2.0.8.3/32): Giles Key Value Metadata
//A dictionary containing metadata results for a single stream. Has 2 keys: -
//UUID: string identifying the stream - Metadata: a map of keys->values of
//metadata
#define BW2_PO_NUM_GILESKEYVALUEMETADATA 33556483
#define BW2_PO_DF_MASK_GILESKEYVALUEMETADATA "2.0.8.3/32"
#define BW2_PO_DF_GILESKEYVALUEMETADATA "2.0.8.3"
#define BW2_PO_MASK_GILESKEYVALUEMETADATA 32

//GilesTimeseriesResponse (2.0.8.4/32): Giles Timeseries Response
//A dictionary containing timeseries results for a query. Has 2 keys: - Nonce:
//the uint32 number corresponding to the query nonce that generated this
//timeseries response - Data: list of GilesTimeseries (2.0.8.5) objects -
//Stats: list of GilesStatistics (2.0.8.6) objects
#define BW2_PO_NUM_GILESTIMESERIESRESPONSE 33556484
#define BW2_PO_DF_MASK_GILESTIMESERIESRESPONSE "2.0.8.4/32"
#define BW2_PO_DF_GILESTIMESERIESRESPONSE "2.0.8.4"
#define BW2_PO_MASK_GILESTIMESERIESRESPONSE 32

//GilesTimeseries (2.0.8.5/32): Giles Timeseries
//A dictionary containing timeseries results for a single stream. has 3 keys: -
//UUID: string identifying the stream - Times: list of uint64 timestamps -
//Values: list of float64 values Times and Values will line up, e.g. index i of
//Times corresponds to index i of values
#define BW2_PO_NUM_GILESTIMESERIES 33556485
#define BW2_PO_DF_MASK_GILESTIMESERIES "2.0.8.5/32"
#define BW2_PO_DF_GILESTIMESERIES "2.0.8.5"
#define BW2_PO_MASK_GILESTIMESERIES 32

//GilesStatistics (2.0.8.6/32): Giles Statistics
//A dictionary containing timeseries results for a single stream. has 3 keys: -
//UUID: string identifying the stream - Times: list of uint64 timestamps -
//Count: list of uint64 values - Min: list of float64 values - Mean: list of
//float64 values - Max: list of float64 values All fields will line up, e.g.
//index i of Times corresponds to index i of Count
#define BW2_PO_NUM_GILESSTATISTICS 33556486
#define BW2_PO_DF_MASK_GILESSTATISTICS "2.0.8.6/32"
#define BW2_PO_DF_GILESSTATISTICS "2.0.8.6"
#define BW2_PO_MASK_GILESSTATISTICS 32

//GilesQueryError (2.0.8.9/32): Giles Query Error
//A dictionary containing an error returned by a query. Has 3 keys: - Query:
//the string query that was sent - Nonce: the nonce in the query request -
//Error: string of the returned error
#define BW2_PO_NUM_GILESQUERYERROR 33556489
#define BW2_PO_DF_MASK_GILESQUERYERROR "2.0.8.9/32"
#define BW2_PO_DF_GILESQUERYERROR "2.0.8.9"
#define BW2_PO_MASK_GILESQUERYERROR 32

//L7G1Raw (2.0.10.1/32): L7G v1 Raw message
//A map containing - srcmac: the MAC address of the sensor - srcip: the IP
//address of the sensor, if available - type: the 16 bit L7G type field -
//popid: the ID of the point of presence that received the packet - poptime:
//the boot time (in us) of the pop when the message was received - brtime: the
//real time (in ns) at the border router when the message was relayed to
//bosswave - rssi: the RSSI of the message at the pop, if available - lqi: the
//LQI of the message at the pop, if available - payload: the raw message
#define BW2_PO_NUM_L7G1RAW 33556993
#define BW2_PO_DF_MASK_L7G1RAW "2.0.10.1/32"
#define BW2_PO_DF_L7G1RAW "2.0.10.1"
#define BW2_PO_MASK_L7G1RAW 32

//L7G1Stats (2.0.10.2/32): L7G v1 stats message
//tbd
#define BW2_PO_NUM_L7G1STATS 33556994
#define BW2_PO_DF_MASK_L7G1STATS "2.0.10.2/32"
#define BW2_PO_DF_L7G1STATS "2.0.10.2"
#define BW2_PO_MASK_L7G1STATS 32

//ChirpFeed (2.0.11.1/32): Chirp Anemometer Feed
//A map containing - vendor: the vendor implementing the algorithm - sensor:
//the anemometer this data is for - algorithm: symbol name of the algorithm
//type/version - tofs: a list of src,dst,val time of flight measurements in
//microseconds - extradata: a list of string extra from the algorithm
#define BW2_PO_NUM_CHIRPFEED 33557249
#define BW2_PO_DF_MASK_CHIRPFEED "2.0.11.1/32"
#define BW2_PO_DF_CHIRPFEED "2.0.11.1"
#define BW2_PO_MASK_CHIRPFEED 32

//HamiltonOT (2.0.11.2/32): Hamilton OT
//A map containing - time: nanoseconds since the epoch - other stuff TODO
#define BW2_PO_NUM_HAMILTONOT 33557250
#define BW2_PO_DF_MASK_HAMILTONOT "2.0.11.2/32"
#define BW2_PO_DF_HAMILTONOT "2.0.11.2"
#define BW2_PO_MASK_HAMILTONOT 32

//HamiltonOR (2.0.11.3/32): Hamilton Orientation
//A map containing - time: nanoseconds since the epoch - other stuff TODO
#define BW2_PO_NUM_HAMILTONOR 33557251
#define BW2_PO_DF_MASK_HAMILTONOR "2.0.11.3/32"
#define BW2_PO_DF_HAMILTONOR "2.0.11.3"
#define BW2_PO_MASK_HAMILTONOR 32

//VenstarInfo (2.0.12.1/32): VenstarInfo
//Consult the venstar API documentation at
//http://developer.venstar.com/restcalls.html
#define BW2_PO_NUM_VENSTARINFO 33557505
#define BW2_PO_DF_MASK_VENSTARINFO "2.0.12.1/32"
#define BW2_PO_DF_VENSTARINFO "2.0.12.1"
#define BW2_PO_MASK_VENSTARINFO 32

//VenstarControl (2.0.12.2/32): VenstarControl
//Consult the documentation
#define BW2_PO_NUM_VENSTARCONTROL 33557506
#define BW2_PO_DF_MASK_VENSTARCONTROL "2.0.12.2/32"
#define BW2_PO_DF_VENSTARCONTROL "2.0.12.2"
#define BW2_PO_MASK_VENSTARCONTROL 32

//String (64.0.1.0/32): String
//A plain string with no rigid semantic meaning. This can be thought of as a
//print statement. Anything that has semantic meaning like a process log should
//use a different schema.
#define BW2_PO_NUM_STRING 1073742080
#define BW2_PO_DF_MASK_STRING "64.0.1.0/32"
#define BW2_PO_DF_STRING "64.0.1.0"
#define BW2_PO_MASK_STRING 32

//FMDIntentString (64.0.1.1/32): FMD Intent String
//A plain string used as an intent for the follow-me display service.
#define BW2_PO_NUM_FMDINTENTSTRING 1073742081
#define BW2_PO_DF_MASK_FMDINTENTSTRING "64.0.1.1/32"
#define BW2_PO_DF_FMDINTENTSTRING "64.0.1.1"
#define BW2_PO_MASK_FMDINTENTSTRING 32

//AccountBalance (64.0.1.2/32): Account balance
//A comma seperated representation of an account and its balance as
//addr,decimal,human_readable. For example
//0x49b1d037c33fdaad75d2532cd373fb5db87cc94c,57203431159181996982272,57203.4311
//Ether  . Be careful in that the decimal representation will frequently be
//bigger than an int64.
#define BW2_PO_NUM_ACCOUNTBALANCE 1073742082
#define BW2_PO_DF_MASK_ACCOUNTBALANCE "64.0.1.2/32"
#define BW2_PO_DF_ACCOUNTBALANCE "64.0.1.2"
#define BW2_PO_MASK_ACCOUNTBALANCE 32

//SpawnpointConfig (67.0.2.0/32): SpawnPoint config
//A configuration file for SpawnPoint (github.com/immesys/spawnpoint)
#define BW2_PO_NUM_SPAWNPOINTCONFIG 1124073984
#define BW2_PO_DF_MASK_SPAWNPOINTCONFIG "67.0.2.0/32"
#define BW2_PO_DF_SPAWNPOINTCONFIG "67.0.2.0"
#define BW2_PO_MASK_SPAWNPOINTCONFIG 32

#endif
